[package]
name = "akashi-img"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { workspace = true }
poise = { workspace = true }
akashi-cache = { path = "../akashi-cache" }

[features]
full-support = ["sticker-support"]
sticker-support = []